<?php

declare(strict_types=1);

namespace SolidAi;

/**
 * Represents a single SOLID violation extracted from the normalized JSON.
 * This is only used to emit GitHub annotations.
 */
final class SolidViolation
{
    public function __construct(
        public readonly string $file,
        public readonly string $principle,
        public readonly string $severity,
        public readonly string $summary,
        public readonly string $suggestion,
        public readonly ?int $line,
        /** @var string[] */
        public readonly array $refactorSteps,
    ) {}
}

/**
 * Reads the normalized JSON generated by parse_response.php
 * and extracts violation objects.
 */
final class SolidViolationReader
{
    /**
     * @return SolidViolation[]
     */
    public function read(string $jsonFile): array
    {
        if (!is_file($jsonFile)) {
            throw new \RuntimeException("Input file not found: {$jsonFile}");
        }

        $raw = file_get_contents($jsonFile);
        if (false === $raw) {
            throw new \RuntimeException("Unable to read file: {$jsonFile}");
        }

        $decoded = json_decode($raw, true);
        if (!is_array($decoded)) {
            throw new \RuntimeException("Invalid JSON format in {$jsonFile}");
        }

        // The normalized JSON is an array of objects:
        // [
        //   {
        //      "file": "...",
        //      "problems": [ { violation }, ... ]
        //   },
        //   ...
        // ]

        $violations = [];

        foreach ($decoded as $fileBlock) {
            if (!is_array($fileBlock)) {
                continue;
            }

            $file = (string) ($fileBlock['file'] ?? '');
            if ('' === $file) {
                continue;
            }

            $problems = $fileBlock['problems'] ?? [];
            if (!is_array($problems)) {
                continue;
            }

            foreach ($problems as $p) {
                if (!is_array($p)) {
                    continue;
                }

                $violations[] = new SolidViolation(
                    file: $file,
                    principle: (string) ($p['principle'] ?? 'N/A'),
                    severity: strtolower((string) ($p['severity'] ?? 'warning')),
                    summary: (string) ($p['summary'] ?? ''),
                    suggestion: (string) ($p['suggestion'] ?? ''),
                    line: isset($p['line']) ? (int) $p['line'] : null,
                    refactorSteps: is_array($p['refactor_steps'] ?? null)
                        ? array_map('strval', $p['refactor_steps'])
                        : []
                );
            }
        }

        return $violations;
    }
}

/**
 * Emits GitHub annotations for a list of violations.
 */
final class GithubAnnotationEmitter
{
    /**
     * @param SolidViolation[] $violations
     */
    public function emitAll(array $violations): void
    {
        foreach ($violations as $v) {
            $level = 'major' === $v->severity
                ? 'error'
                : 'warning';

            $title = "SOLID {$v->principle} ({$v->severity})";

            $body = $v->summary;
            if ('' !== $v->suggestion) {
                $body .= "\nSuggestion: ".$v->suggestion;
            }
            if ([] !== $v->refactorSteps) {
                $body .= "\nRefactor steps:";
                foreach ($v->refactorSteps as $step) {
                    $body .= "\n- {$step}";
                }
            }

            $this->emit($level, $v->file, $v->line, $title, $body);
        }
    }

    /**
     * Emits a single GitHub annotation line.
     */
    private function emit(string $level, string $file, ?int $line, string $title, string $body): void
    {
        $titleSafe = $this->escape($title);
        $bodySafe = $this->escape($body);

        if (null !== $line && $line > 0) {
            printf(
                "::%s file=%s,line=%d,title=%s::%s\n",
                $level,
                $file,
                $line,
                $titleSafe,
                $bodySafe
            );
        } else {
            printf(
                "::%s file=%s,title=%s::%s\n",
                $level,
                $file,
                $titleSafe,
                $bodySafe
            );
        }
    }

    /**
     * GitHub command escaping rules.
     */
    private function escape(string $text): string
    {
        return strtr($text, [
            '%' => '%25',
            "\r" => '%0D',
            "\n" => '%0A',
        ]);
    }
}

// -----------------------------------------------------------------------------
// CLI execution
// -----------------------------------------------------------------------------

if ($argc < 2) {
    fwrite(STDERR, "Usage: php emit_annotations.php <normalized_json_file>\n");

    exit(1);
}

$input = $argv[1];

try {
    $reader = new SolidViolationReader();
    $violations = $reader->read($input);

    if ([] !== $violations) {
        $emitter = new GithubAnnotationEmitter();
        $emitter->emitAll($violations);
    }
} catch (\RuntimeException $e) {
    fwrite(STDERR, 'Error: '.$e->getMessage()."\n");

    exit(1);
}

exit(0);
